export const FETCH_DOCUMENTS_LIST_REQUEST = "FETCH_DOCUMENTS_LIST_REQUEST";
export const FETCH_DOCUMENTS_LIST_SUCCESS = "FETCH_DOCUMENTS_LIST_SUCCESS";
export const FETCH_DOCUMENTS_LIST_FAILURE = "FETCH_DOCUMENTS_LIST_FAILURE";
