export const FETCH_DOCUMENT_REQUEST = "FETCH_DOCUMENT_REQUEST";
export const FETCH_DOCUMENT_SUCCESS = "FETCH_DOCUMENT_SUCCESS";
export const FETCH_DOCUMENT_FAILURE = "FETCH_DOCUMENT_FAILURE";

export const CLEAR_DOCUMENT_REQUEST = "CLEAR_DOCUMENT_REQUEST";

export const NEW_DOCUMENT_REQUEST = "NEW_DOCUMENT_REQUEST";
export const NEW_DOCUMENT_SUCCESS = "NEW_DOCUMENT_SUCCESS";
export const NEW_DOCUMENT_FAILURE = "NEW_DOCUMENT_FAILURE";

export const FETCH_SEARCH_RESULTS_REQUEST = "FETCH_SEARCH_RESULTS_REQUEST";
export const FETCH_SEARCH_RESULTS_SUCCESS = "FETCH_SEARCH_RESULTS_SUCCESS";
export const FETCH_SEARCH_RESULTS_FAILURE = "FETCH_SEARCH_RESULTS_FAILURE";

export const CLEAR_SEARCH_RESULTS_REQUEST = "CLEAR_SEARCH_RESULTS_REQUEST";
