export const FETCH_DOCUMENT_REQUEST = "FETCH_DOCUMENT_REQUEST";
export const FETCH_DOCUMENT_SUCCESS = "FETCH_DOCUMENT_SUCCESS";
export const FETCH_DOCUMENT_FAILURE = "FETCH_DOCUMENT_FAILURE";

export const CLEAR_DOCUMENT_REQUEST = "CLEAR_DOCUMENT_REQUEST";

export const NEW_DOCUMENT_REQUEST = "NEW_DOCUMENT_REQUEST";
export const NEW_DOCUMENT_SUCCESS = "NEW_DOCUMENT_SUCCESS";
export const NEW_DOCUMENT_FAILURE = "NEW_DOCUMENT_FAILURE";
